import numpy as np
from llm import chat


def answer_question(query, chunks, bm25, db, summary, reranker, recent_history, messages_for_llm):
    """
    Runs the full agentic RAG pipeline for a single question:
    router -> rewrite -> plan -> decompose -> multi-query -> hybrid retrieval
    -> rerank -> evidence check (+fallback) -> answer -> verify (+self-correct).

    `recent_history` is a pre-formatted string of the last few turns (for prompts).
    `messages_for_llm` is the list of {"role", "content"} dicts for chat history
    (built by the caller from st.session_state, mirroring the notebook's `messages`).

    Returns a dict: {"type": "summary"|"memory"|"answer", "content": ..., "sources": [...]}
    """

    ##### Router Agent
    router_prompt = f"""
    You are a retrieval routing agent for a question-answering system
    about ONE specific document.

    Document Summary:
    {summary}

    Question:
    {query}

    Choose exactly one:

    SUMMARY
    - Only if the user asks for:
    summary
    overview
    brief
    abstract
    gist
    main points

    MEMORY
    - Only if the user asks about previous conversation

    OFF_TOPIC
    - The question asks for advice, ideas, opinions, or help with a task,
      rather than asking what the document says. This is OFF_TOPIC even
      if the document's subject matter could theoretically inspire an
      answer.
    - Example: Document Summary is about cancer treatment research.
      Question: "what startup can I build as a student?" -> OFF_TOPIC.
      This is OFF_TOPIC because the user is asking for startup ideas,
      not asking what the document says, even though the document's
      subject (cancer) could be used to brainstorm a startup idea.
    - Other examples: general life advice, coding help, personal
      opinions, small talk, or any question not asking what the
      document itself states.

    RETRIEVAL
    - The question asks what the document says, states, describes,
      explains, or reports about its subject matter.

    When uncertain between OFF_TOPIC and RETRIEVAL, ask: "Is the user
    asking me to report what the document says, or asking me to use the
    document's topic as a springboard for something else (advice, ideas,
    opinions, a new task)?" If it's the latter, choose OFF_TOPIC.

    Reply with only one word:
    SUMMARY
    MEMORY
    OFF_TOPIC
    RETRIEVAL
    """
    router_response = chat(model="llama3.1:8B", messages=[
        {"role": "user", "content": router_prompt}
    ])
    router_decision = router_response["message"]["content"].strip().upper()

    NOT_FOUND_MESSAGE = "I could not find the answer in the document."

    if router_decision == "SUMMARY":
        return {"type": "summary", "content": summary, "sources": []}
    elif router_decision == "MEMORY":
        return {"type": "memory", "content": recent_history, "sources": []}
    elif "OFF_TOPIC" in router_decision:
        # Short-circuit before any retrieval or answer generation happens.
        # The refusal message is fixed in code, not generated by the model,
        # so there is no opportunity for it to be paraphrased or padded
        # with unrelated brainstorming.
        return {"type": "answer", "content": NOT_FOUND_MESSAGE, "sources": []}

    #### query rewriting

    rewrite_prompt = f"""
    Rewrite the user's question into a standalone search query.

    Rules:
    - Do NOT answer the question.
    - Do NOT explain.
    - Do NOT summarize.
    - Return ONLY the rewritten question.
    - Return exactly one line.

    Conversation:
    {recent_history}

    Question:
    {query}

    Rewritten Question:
    """

    rewrite_response = chat(model="llama3.1:8B", messages=[
        {"role": "user", "content": rewrite_prompt}
    ])
    rewritten_query = rewrite_response["message"]["content"].replace("*", "").removeprefix("assistant").strip().split("\n")[0]

    #retrieval planner agent
    planner_prompt = f"""
    Question:
    {rewritten_query}

    Create a retrieval plan.

    Break the question into information needs.

    Return one step per line.

    Example:

    Question:
    What causes cancer and how is it treated?

    Plan:
    Find causes of cancer
    Find treatments for cancer
    """
    planner_response = chat(
        model="llama3.1:8B",
        messages=[
            {
                "role": "user",
                "content": planner_prompt
            }
        ]
    )

    plan = planner_response["message"]["content"]

    #query decomposition into multiple queries for better retrieval diversity

    decomposition_prompt = f"""
    Break down the rewritten question into smaller independent questions.

    If decomposition is not needed,
    return the original question only.
    Question:
    {rewritten_query}

    Return one question per line.
    """
    decomposition_response = chat(model="llama3.1:8B", messages=[
        {"role": "user", "content": decomposition_prompt}
    ])
    sub_queries = []
    for q in decomposition_response["message"]["content"].split("\n"):
        q = q.strip()
        if not q:
            continue
        if "here are" in q.lower():
            continue
        q = q.lstrip("123456789.- ")
        sub_queries.append(q)

    if not sub_queries:
        sub_queries = [rewritten_query]

    queries = []
    for sub_q in sub_queries:
        queries.append(sub_q)
        multi_query_prompt = f"""
        Generate 3 different paraphrased versions
        of this question.
        Question:
        {sub_q}

        Return one query per line.
        """
        multi_query_response = chat(
            model="llama3.1:8B",
            messages=[
                {
                    "role": "user",
                    "content": multi_query_prompt
                }
            ]
        )

        for q in multi_query_response["message"]["content"].split("\n"):
            q = q.strip()
            if q:
                q = q.lstrip("123456789.- ")
                queries.append(q)

    queries = list(dict.fromkeys(queries))

    #retrieve relevant documents
    results = []
    for q in queries:
        docs = db.similarity_search(q, k=3)
        results.extend(docs)
    bm25_scores = np.zeros(len(chunks))
    for q in queries:
        bm25_scores += bm25.get_scores(q.split())
    top_k = np.argsort(bm25_scores)[-3:][::-1]
    all_docs = []
    #get chunk id:
    for result in results:
        chunk_id = result.metadata["chunk_id"]
        for i in range(chunk_id - 2, chunk_id + 3):
            if 0 <= i < len(chunks):
                all_docs.append(chunks[i])
    #bm25 docs
    for idx in top_k:
        all_docs.append(chunks[idx])

    # remove duplicates
    unique_docs = {}
    for doc in all_docs:
        unique_docs[doc.metadata["chunk_id"]] = doc
    all_docs = list(unique_docs.values())

    doc_scores = []

    for doc in all_docs:
        pairs = []
        for sub_q in sub_queries:
            pairs.append(
                [
                    sub_q,
                    doc.page_content
                ]
            )

        scores = reranker.predict(pairs)
        final_score = max(scores)
        best_sub_q_idx = int(np.argmax(scores))
        doc_scores.append(
            (
                final_score,
                best_sub_q_idx,
                doc
            )
        )

    # Guarantee each sub-question gets a fair share of the final context
    # instead of letting one sub-question's chunks dominate the global top-5
    # (this was the bug: a compound question like "treatments and causes"
    # would lose the "causes" chunks entirely if treatment chunks scored
    # higher overall, even though decomposition correctly split them out).
    TOTAL_SLOTS = 5
    per_sub_q_quota = max(1, TOTAL_SLOTS // max(1, len(sub_queries)))

    top_docs = []
    seen_chunk_ids = set()

    for sub_q_idx in range(len(sub_queries)):
        candidates = [
            (score, doc) for score, best_idx, doc in doc_scores
            if best_idx == sub_q_idx and doc.metadata["chunk_id"] not in seen_chunk_ids
        ]
        candidates.sort(key=lambda x: x[0], reverse=True)
        for score, doc in candidates[:per_sub_q_quota]:
            top_docs.append(doc)
            seen_chunk_ids.add(doc.metadata["chunk_id"])

    # Fill any remaining slots with the next-highest-scoring docs overall
    if len(top_docs) < TOTAL_SLOTS:
        remaining = [
            (score, doc) for score, best_idx, doc in doc_scores
            if doc.metadata["chunk_id"] not in seen_chunk_ids
        ]
        remaining.sort(key=lambda x: x[0], reverse=True)
        for score, doc in remaining[:TOTAL_SLOTS - len(top_docs)]:
            top_docs.append(doc)
            seen_chunk_ids.add(doc.metadata["chunk_id"])

    combined_context = "\n\n".join([doc.page_content for doc in top_docs])

    #evidence selection prompt
    evidence_prompt = f"""
    Question: {rewritten_query}

    Retrieved Context:
    {combined_context}
    Is there enough information in the retrieved context to answer the question? 
    Reply with only:

    YES -> if the answer can be found in the retrieved context

    NO -> if the retrieved context does not contain enough information to answer the question
    """
    evidence_response = chat(model="llama3.1:8B", messages=[
        {"role": "user", "content": evidence_prompt}
    ])
    evidence_decision = evidence_response["message"]["content"].strip().upper().split()[0]

    if evidence_decision == "NO":
        fallback_docs = []
        for q in queries:
            fallback_docs.extend(db.similarity_search(q, k=5))
        unique_docs = {}
        for doc in fallback_docs:
            unique_docs[doc.metadata["chunk_id"]] = doc
        fallback_docs = list(unique_docs.values())

        pairs = [
            [rewritten_query, doc.page_content]
            for doc in fallback_docs
        ]

        scores = reranker.predict(pairs)

        sorted_docs = sorted(
            zip(scores, fallback_docs),
            key=lambda x: x[0],
            reverse=True
        )

        top_docs = [
            doc
            for score, doc in sorted_docs[:5]
        ]

        combined_context = "\n\n".join(
            [doc.page_content for doc in top_docs])
        prompt = f"""
        You are a document question answering system.

        Use ONLY the document context.

        Document Summary:
        {summary}

        Document Context:
        {combined_context}

        Current Question:
        {query}

        Answer:
        """

    else:
        prompt = f"""
        You are a document question answering system.

        Use ONLY the document context below. Never use outside knowledge,
        even to fill in a gap or add a "for context" explanation — if it is
        not in the Document Context, it does not exist for this answer.

        Answer in 10 sentences.

        The question may have multiple parts. Handle each part independently:
        - If a part is answered in the context, answer it directly using
          only what the context says. Do not add a disclaimer for that part.
        - If a part is NOT answered in the context, say so for that part
          only, in one short sentence (e.g. "The document does not cover
          the causes of cancer."). Do not guess, and do not pull in
          outside knowledge to compensate.
        - Do not contradict yourself: if you state a fact from the context,
          do not also claim the document doesn't address it.

        If the question, in its entirety, is unrelated to the Document
        Context and Document Summary (for example: general advice, coding
        help, startup ideas, personal opinions, or anything the document
        is not about), your ENTIRE response must be exactly this one line
        and NOTHING else — no brainstorming, no "however", no follow-up
        suggestions, no ideas "inspired by" the document:

        I could not find the answer in the document.

        Document Summary:
        {summary}

        Document Context:
        {combined_context}

        Current Question:
        {query}

        Answer:
        """

    # send history and prompt to model and get response
    response = chat(model="llama3.1:8B", messages=[
        *messages_for_llm,
        {"role": "user", "content": prompt}]
    )
    answer = response["message"]["content"]
    answer = answer.removeprefix("assistant").strip()

    verification_prompt = f"""
    Question:
    {query}

    Sub Questions:
    {sub_queries}

    Answer:
    {answer}

    Did the answer fully answer every sub_question?

    Reply only:

    YES
    NO
    """

    verification_response = chat(model="llama3.1:8B", messages=[
        {
            "role": "user",
            "content": verification_prompt
        }
    ])
    verification_decision = (
        verification_response["message"]["content"].strip().upper()
    )

    #self correction
    if verification_decision == "NO":
        fallback_docs = []
        for q in queries:
            fallback_docs.extend(
                db.similarity_search(q, k=10)
            )
        unique_docs = {}
        for doc in fallback_docs:
            unique_docs[doc.metadata["chunk_id"]] = doc
        fallback_docs = list(unique_docs.values())
        pairs = [
            [rewritten_query, doc.page_content]
            for doc in fallback_docs
        ]

        scores = reranker.predict(pairs)
        sorted_docs = sorted(
            zip(scores, fallback_docs),
            key=lambda x: x[0],
            reverse=True
        )

        top_docs = [
            doc
            for score, doc in sorted_docs[:10]
        ]

        combined_context = "\n\n".join(
            [doc.page_content for doc in top_docs]
        )

        prompt = f"""
        You are a document question answering system.

        Use ONLY the document context below. Never use outside knowledge,
        even to fill in a gap or add a "for context" explanation — if it is
        not in the Document Context, it does not exist for this answer.

        Answer in 10 sentences.

        The question may have multiple parts. Handle each part independently:
        - If a part is answered in the context, answer it directly using
          only what the context says. Do not add a disclaimer for that part.
        - If a part is NOT answered in the context, say so for that part
          only, in one short sentence (e.g. "The document does not cover
          the causes of cancer."). Do not guess, and do not pull in
          outside knowledge to compensate.
        - Do not contradict yourself: if you state a fact from the context,
          do not also claim the document doesn't address it.

        If the question, in its entirety, is unrelated to the Document
        Context and Document Summary (for example: general advice, coding
        help, startup ideas, personal opinions, or anything the document
        is not about), your ENTIRE response must be exactly this one line
        and NOTHING else — no brainstorming, no "however", no follow-up
        suggestions, no ideas "inspired by" the document:

        I could not find the answer in the document.

        Document Summary:
        {summary}

        Document Context:
        {combined_context}

        Current Question:
        {query}

        Answer:
        """

        response = chat(
            model="llama3.1:8B",
            messages=[
                *messages_for_llm,
                {"role": "user", "content": prompt}
            ]
        )

        answer = response["message"]["content"]
        answer = answer.removeprefix("assistant").strip()

    # Safety net 1: even with explicit prompting, the model sometimes emits
    # the refusal line and then keeps going with unrelated content anyway
    # (e.g. "I could not find the answer... However, here are some ideas").
    # If the refusal appears anywhere in the answer, treat it as the
    # complete answer and discard anything the model added after/around it.
    if NOT_FOUND_MESSAGE.rstrip(".").lower() in answer.lower():
        answer = NOT_FOUND_MESSAGE
        sources = []
        return {"type": "answer", "content": answer, "sources": sources}

    # Safety net 2: independent grounding check. The router can misclassify
    # a question as RETRIEVAL when it's actually asking for advice/ideas
    # built on the document's topic rather than asking what the document
    # says. This check looks at the ACTUAL generated answer against the
    # ACTUAL retrieved context (not just the question in isolation, which
    # is all the router sees) and catches cases where the model invented
    # suggestions, ideas, or advice not stated in the document.
    grounding_prompt = f"""
    Document Context:
    {combined_context}

    Generated Answer:
    {answer}

    Does the Generated Answer ONLY state facts that are present in the
    Document Context? Answer NO if the Generated Answer adds suggestions,
    ideas, advice, or recommendations that are not explicitly stated in
    the Document Context (for example, brainstormed "startup ideas",
    "you might want to" suggestions, or any content presented as
    inspired by the document rather than stated in it).

    Reply with only one word:
    YES
    NO
    """
    grounding_response = chat(model="llama3.1:8B", messages=[
        {"role": "user", "content": grounding_prompt}
    ])
    grounding_decision = grounding_response["message"]["content"].strip().upper()

    if "NO" in grounding_decision and "YES" not in grounding_decision:
        answer = NOT_FOUND_MESSAGE
        sources = []
    else:
        sources = sorted({doc.metadata["page"] + 1 for doc in top_docs})

    return {"type": "answer", "content": answer, "sources": sources}